- name: Node.js
  logo: Node.js
  url: https://nodejs.org/en/
  color: '#339933'
  projects:
    - url: https://github.com/ryadios/empress
    - url: https://github.com/ryadios/social-coder

- name: Next.js
  logo: Next.js
  url: https://nextjs.org/
  color: '#000000'
  projects:
    - url: https://github.com/ryadios/zenith

- name: Typescript
  logo: TypeScript
  url: https://www.typescriptlang.org/
  color: '#3178C6'
  color: '#000000'
  projects:
    - url: https://github.com/ryadios/echo

- name: Problem Solving
  logo: LeetCode
  url: https://leetcode.com/
  color: '#FFA116'
  projects:
    - url: https://github.com/ryadios/dsa-course

- name: Shell
  logo: GNU Bash
  url: https://www.gnu.org/
  color: '#4EAA25'
  projects:
    - url: https://github.com/ryadios/.dotfiles